import 'package:flutter/material.dart';
import 'package:ijato/app/models/service.dart';

class SolicitationController with ChangeNotifier {
  List<Service> services = [
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
    Service(
      date: "30/05/2024",
      time: "08:00 às 09:00",
      name: "Vinicius Sobreira",
      vehicle: "Carro",
      brand: "Fiat",
      model: "Siena",
      plate: "OSF-0240",
      service: "Higienização completa",
      status: ServiceStatus.pending,
    ),
  ];

  void changeStatus(int index, ServiceStatus status) {
    services[index].status = status;
    notifyListeners();
  }
}
